import img from './img/1.png';

export default [

    {
        id: 1,
        codigo: "1",
        descripcion: "Aretes modelo rosetta confeccionados en oro blanco de 18k con un diamante central y cinco pétalos de diamantes, todos de corte excelente.(Todas las joyas se pueden personalizar a tu gusto)",
        tipo: "anillo",
        color: "plata",
        corte: "medio",
        tono: "d-f",
        ocasion: "compromiso",
        diamante: "solo",
        imagen: `${img}`,
    },
    {
        id: 2,
        codigo: "2",
        descripcion: "Aretes modelo rosetta confeccionados en oro blanco de 18k con un diamante central y cinco pétalos de diamantes, todos de corte excelente.(Todas las joyas se pueden personalizar a tu gusto)",
        tipo: "anillo",
        color: "oro",
        corte: "medio",
        tono: "g-j",
        ocasion: "matrimonio",
        diamante: "solo",
        imagen: `${img}`,
    },
    {
        id: 3,
        codigo: "3",
        descripcion: "Aretes modelo rosetta confeccionados en oro blanco de 18k con un diamante central y cinco pétalos de diamantes, todos de corte excelente.(Todas las joyas se pueden personalizar a tu gusto)",
        tipo: "anillo",
        color: "blanco",
        corte: "medio",
        tono: "k-m",
        ocasion: "compromiso",
        diamante: "solo",
        imagen: `${img}`,
    },
    {
        id: 4,
        codigo: "4",
        descripcion: "Aretes modelo rosetta confeccionados en oro blanco de 18k con un diamante central y cinco pétalos de diamantes, todos de corte excelente.(Todas las joyas se pueden personalizar a tu gusto)",
        tipo: "aretes",
        color: "blanco",
        corte: "medio",
        tono: "n-r",
        ocasion: "toda-ocasion",
        diamante: "solo",
        imagen: `${img}`,
    },
    {
        id: 5,
        codigo: "5",
        descripcion: "Aretes modelo rosetta confeccionados en oro blanco de 18k con un diamante central y cinco pétalos de diamantes, todos de corte excelente.(Todas las joyas se pueden personalizar a tu gusto)",
        tipo: "aretes",
        color: "rosa",
        corte: "medio",
        tono: "s-z",
        ocasion: "toda-ocasion",
        diamante: "solo",
        imagen: `${img}`,
    },
    {
        id: 6,
        codigo: "6",
        descripcion: "Aretes modelo rosetta confeccionados en oro blanco de 18k con un diamante central y cinco pétalos de diamantes, todos de corte excelente.(Todas las joyas se pueden personalizar a tu gusto)",
        tipo: "dije",
        color: "rosa",
        corte: "medio",
        tono: "s-z",
        ocasion: "toda-ocasion",
        diamante: "solo",
        imagen: `${img}`,
    },
    {
        id: 7,
        codigo: "7",
        descripcion: "Aretes modelo rosetta confeccionados en oro blanco de 18k con un diamante central y cinco pétalos de diamantes, todos de corte excelente.(Todas las joyas se pueden personalizar a tu gusto)",
        tipo: "anillo",
        color: "rosa",
        corte: "medio",
        tono: "s-z",
        ocasion: "compromiso",
        diamante: "varios",
        imagen: `${img}`,
    },
];

// import img from './img/1.png';

// export default [

//     {
//         id: 1,
//         codigo: "A317",
//         descripcion: "Aretes modelo rosetta confeccionados en oro blanco de 18k con un diamante central y cinco pétalos de diamantes, todos de corte excelente.                                                                                                                                   (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "aretes",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 2,
//         codigo: "A321",
//         descripcion: "Aretes modelo solitario confeccionados en oro amarillo de 18k con dos diamantes centrales engastados en uñas, todos de corte excelente.                                                                                                          (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "aretes",
//         color: "amarillo",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 3,
//         codigo: "A320",
//         descripcion: "   Aretes modelo media bola, clásicos, confeccionados en oro amarillo de 18k.                                                                                                       (Todas las joyas se pueden personalizar a tu gusto) ",
//         tipo: "aretes",
//         color: "amarillo",
//         ocasion: "toda-ocasion",
//         diamante: "",
//         imagen: `${img}`,
//     }, {
//         id: 4,
//         codigo: "A312",
//         descripcion: "Aretes modelo estrella poste confeccionados en oro blanco de 18k con ciento sesenta diamantes engastados al paveé , todos de corte excelente.                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "aretes",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 5,
//         codigo: "A317",
//         descripcion: "Aretes modelo rosetta confeccionados en oro amarillo de 18k con un diamante central y cinco pétalos de diamantes, todos de corte excelente.                                                                                                                                   (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "aretes",
//         color: "amarillo",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 6,
//         codigo: "A326",
//         descripcion: "Aretes modelo rosetta redonda confeccionados en oro blanco de 18k con catorce diamantes engastados en uñas, todos de corte excelente.                                                                                                                  (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "aretes",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 7,
//         codigo: "A327",
//         descripcion: "Aretes Amatista confeccionados en oro amarillo de 18k con dos amatistas pear shape acompañadas de diamantes amarillo canario engastados en uñas, todos de corte excelente.                                                                                              (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "aretes",
//         color: "amarillo",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 8,
//         codigo: "A315",
//         descripcion: "Aretes modelo gotas de diamante, confeccionados en oro blanco de 18k con doscientos cincuenta diamantes engastados al paveé , todos de corte excelente.                                                                                                                   (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "aretes",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 9,
//         codigo: "A328",
//         descripcion: "Aretes modelo doble gota, confeccionados en oro blanco de 18k con ciento catorce diamantes engastados en uñas , todos de corte excelente.                                                                                                                  (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "aretes",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 10,
//         codigo: "A308",
//         descripcion: "Aretes modelo estrella de mar, confeccionados en oro blanco de 18k con ochenta y dos diamantes engastados en uñas , todos de corte excelente.                                                                                                                  (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "aretes",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 11,
//         codigo: "A329",
//         descripcion: "Aretes modelo florcita, confeccionados en oro amarillo de 18k con dos diamantes centrales engastados al bisel , todos de corte excelente.                                                                                                                  (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "aretes",
//         color: "amarillo",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 12,
//         codigo: "D426",
//         descripcion: "Dije Modelo Lazo confeccionado en oro amarillo con detalles de oro blanco de 18kcon tres diamantes engastados al tope, todos de corte excelente.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "dije",
//         color: "amarillo",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 13,
//         codigo: "D427",
//         descripcion: "Dije Modelo Hoja confeccionado en oro blanco  de 18kcon setenta y dos diamantes engastados en uñas, todos de corte excelente.                                                                                                                                                            (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "dije",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 14,
//         codigo: "D428",
//         descripcion: "Dije Modelo Solitario confeccionado en oro blanco de 18k con un diamante central engastado en bisel con diseño, de corte excelente.                                                                                                                                                                (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "dije",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 15,
//         codigo: "D407",
//         descripcion: "Dije Modelo óvalo doble confeccionado en oro blanco de 18k con ciento once diamantes engastado en uñas, todos de corte excelente.                                                                                                                                                   (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "dije",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 16,
//         codigo: "D429",
//         descripcion: "Dije Modelo Gota confeccionado en oro blanco de 18k con un diamante central pear shape   acompañado por quince diamantes engastados en uñas, todos de corte excelente.                                                                                                                                (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "dije",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 17,
//         codigo: "D430",
//         descripcion: "Dije Corazón azul confeccionado en oro blanco de 18k con un diamante central azul engastado al tope,  de corte excelente.                                                                                                                                                                                   (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "dije",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 18,
//         codigo: "S217",
//         descripcion: "Sortija Modelo Rosita confeccionado en oro amarillo de  18kcon un diamante central engastado al bisel y once diamantes alrededor engastados en uñas, todos de corte excelente.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 19,
//         codigo: "S223",
//         descripcion: "Sortija Modelo Medio Riviere confeccionado en oro amarillo de  18kcon trece diamantes engastados en uñas, todos de corte excelente.                                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 20,
//         codigo: "S223",
//         descripcion: "Sortija Modelo florcita confeccionado en oro amarillo de  18kcon dos diamantes engastados al bisel, todos de corte excelente.                                                                                                                                                                           (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 21,
//         codigo: "S218",
//         descripcion: "Sortija Modelo Rosita confeccionado en oro blanco de  18kcon un diamante central engastado al bisel y once diamantes alrededor engastados en uñas, todos de corte excelente.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 22,
//         codigo: "S227",
//         descripcion: "Sortija Modelo Aro blue & white confeccionado en oro blanco de  18kcon trece diamantes azules y blancos engastados en uñas, todos de corte excelente.                                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 23,
//         codigo: "S226",
//         descripcion: "Sortija Modelo medio riviere blue & white confeccionado en oro blanco de  18kcon nueve diamantes azules y blancos engastados en uñas, todos de corte excelente.                                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 24,
//         codigo: "S223",
//         descripcion: "Sortija Modelo Medio Riviere banda delgada confeccionado en oro blanco de  18kcon veinticinco diamantes engastados en uñas, todos de corte excelente.                                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 25,
//         codigo: "S205",
//         descripcion: "Sortija Modelo Medio Riviere confeccionado en oro blanco de  18kcon trece diamantes engastados al grano con biselado, todos de corte excelente.                                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 26,
//         codigo: "S221",
//         descripcion: "Sortija Modelo Rosetta confeccionado en oro blanco de  18kcon siete diamantes engastados en uñas,  todos de corte excelente.                                                                                                                                                                (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "toda-ocasion",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 27,
//         codigo: "AM001",
//         descripcion: "Aros de matrimonio clásicos media caña confeccionados en oro amarillo de 18k                                                                                                                                    (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "aros",
//         color: "amarillo",
//         ocasion: "matrimonio",
//         diamante: "ninguno",
//         imagen: `${img}`,
//     }, {
//         id: 28,
//         codigo: "AM002",
//         descripcion: "Aros de matrimonio clásicos media caña confeccionados en oro blanco de 18k                                                                                                                                    (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "aros",
//         color: "blanco",
//         ocasion: "matrimonio",
//         diamante: "ninguno",
//         imagen: `${img}`,
//     }, {
//         id: 29,
//         codigo: "AM003",
//         descripcion: "Aros de matrimonio  media caña con diseño corte hoja, confeccionados en oro amarillo de 18k  con tres diamantes engastados al grano, todos de corte excelente.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "aros",
//         color: "amarillo",
//         ocasion: "matrimonio",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 30,
//         codigo: "AM004",
//         descripcion: "Aros de matrimonio  media caña con  diseño corte hoja, confeccionados en oro blanco de 18k  con tres diamantes engastados al grano, todos de corte excelente.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "aros",
//         color: "blanco",
//         ocasion: "matrimonio",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 31,
//         codigo: "3009",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro amarillo y oro blanco de 18k.  Se recomienda colocar diamantes desde 0,30 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 32,
//         codigo: "4021",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro amarillo  de 18k.  Se recomienda colocar diamantes desde 0,20 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 33,
//         codigo: "2503",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro amarillo  de 18k.  Se recomienda colocar diamantes desde 0,20 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 34,
//         codigo: "2009",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro amarillo  de 18k.  Se recomienda colocar diamantes desde 0,18 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 35,
//         codigo: "4011",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro amarillo  de 18k.  Se recomienda colocar diamantes desde 0,23 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 36,
//         codigo: "4023",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro amarillo  de 18k con un Diamante central Heart Shape.  Se recomienda colocar diamantes desde 0,40 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                                                       (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 37,
//         codigo: "4025",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro amarillo  de 18k.  Se recomienda colocar diamantes desde 0,30 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 38,
//         codigo: "4013",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro amarillo  de 18k.  Se recomienda colocar diamantes desde 0,30 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 39,
//         codigo: "3010",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro blanco  de 18k.  Se recomienda colocar diamantes desde 0,30 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 40,
//         codigo: "1508",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro blanco  de 18k.  Se recomienda colocar diamantes desde 0,20 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 41,
//         codigo: "4022",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro blanco  de 18k.  Se recomienda colocar diamantes desde 0,30 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 42,
//         codigo: "4014",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro blanco  de 18k.  Se recomienda colocar diamantes desde 0,30 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 43,
//         codigo: "4002",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro amarillo  de 18k.  Se recomienda colocar diamantes desde 0,35 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 44,
//         codigo: "4012",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro amarillo  de 18k.  Se recomienda colocar diamantes desde 0,23 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 45,
//         codigo: "4024",
//         descripcion: "Anillo de compromiso solitario confeccionado en oro amarillo  de 18k.  Se recomienda colocar diamantes desde 0,20 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "compromiso",
//         diamante: "solo",
//         imagen: `${img}`,
//     }, {
//         id: 46,
//         codigo: "4026",
//         descripcion: "Anillo de compromiso Modelo Pure Elegance  confeccionado en oro blanco con detalles de oro amarillo de 18k.  La pieza cuenta con un total de veinte diamantes. Se recomienda colocar un diamante central desde 0,40 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "compromiso",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 47,
//         codigo: "4028",
//         descripcion: "Anillo de compromiso  confeccionado en oro blanco de 18k.  La pieza cuenta con un Diamante central azul acompañado por veinticuatro diamantes blancos. Se recomienda colocar un diamante central desde 0,40 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "compromiso",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 48,
//         codigo: "4030",
//         descripcion: "Anillo de compromiso Modelo Petite Elegance  confeccionado en oro blanco con detalles de oro amarillo de 18k.  La pieza cuenta con un total de once diamantes. Se recomienda colocar un diamante central desde 0,30 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                 (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco" || "amarillo",
//         ocasion: "compromiso",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 49,
//         codigo: "4032",
//         descripcion: "Anillo de compromiso  confeccionado en oro blanco de 18k.  La pieza cuenta con un total de cincuenta y cinco diamantes. Se recomienda colocar un diamante central desde 0,40 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                               (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "compromiso",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 50,
//         codigo: "5014",
//         descripcion: "Anillo de compromiso  confeccionado en oro blanco de 18k.  La pieza cuenta con un total de veinticinco diamantes. Se recomienda colocar un diamante central desde 0,30 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                               (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "compromiso",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 51,
//         codigo: "3102",
//         descripcion: "Anillo de compromiso  confeccionado en oro blanco de 18k.  La pieza cuenta con un total de trece diamantes. Se recomienda colocar un diamante central desde 0,30 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                               (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "blanco",
//         ocasion: "compromiso",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 52,
//         codigo: "4027",
//         descripcion: "Anillo de compromiso  confeccionado en oro amarillo de 18k.  La pieza cuenta con un total de trece diamantes. Se recomienda colocar un diamante central desde 0,30 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                               (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "compromiso",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 53,
//         codigo: "4029",
//         descripcion: "Anillo de compromiso  confeccionado en oro amarillo y detalles de oro blanco de 18k .  La pieza cuenta con un total de doce diamantes. Se recomienda colocar un diamante central desde 0,50 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                               (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "compromiso",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 54,
//         codigo: "3107",
//         descripcion: "Anillo de compromiso  confeccionado en oro amarillo y detalles de oro blanco de 18k .  La pieza cuenta con un total de once diamantes. Se recomienda colocar un diamante central desde 0,30 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                               (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo" || "blanco",
//         ocasion: "compromiso",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 55,
//         codigo: "5007",
//         descripcion: "Anillo de compromiso  confeccionado en oro amarillo y detalles de oro blanco de 18k .  La pieza cuenta con un total de veinticinco diamantes. Se recomienda colocar un diamante central desde 0,35 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                               (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo" || "blanco",
//         ocasion: "compromiso",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 56,
//         codigo: "3101",
//         descripcion: "Anillo de compromiso  confeccionado en oro amarillo y detalles de oro blanco de 18k .  La pieza cuenta con un total de once diamantes. Se recomienda colocar un diamante central desde 0,30 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                               (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo" || "blanco",
//         ocasion: "compromiso",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 57,
//         codigo: "5011",
//         descripcion: "Anillo de compromiso  confeccionado en oro amarillo y detalles de oro blanco de 18k .  La pieza cuenta con un total de tres diamantes. Se recomienda colocar un diamante central desde 0,30 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                               (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo" || "blanco",
//         ocasion: "compromiso",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 58,
//         codigo: "1801",
//         descripcion: "Anillo de compromiso  confeccionado en oro amarillo de 18k .  La pieza cuenta con un total de trece diamantes. Se recomienda colocar un diamante central desde 0,20 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                               (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "compromiso",
//         diamante: "varios",
//         imagen: `${img}`,
//     }, {
//         id: 59,
//         codigo: "4031",
//         descripcion: "Anillo de compromiso  confeccionado en oro amarillo de 18k .  La pieza cuenta con un total de quince diamantes. Se recomienda colocar un diamante central desde 0,40 Carats. Diamantes de corte excelente y certificación GIA.                                                                                                                                               (Todas las joyas se pueden personalizar a tu gusto)",
//         tipo: "anillo",
//         color: "amarillo",
//         ocasion: "compromiso",
//         diamante: "varios",
//         imagen: `${img}`,
//     }
// ];